### ISSUE TITLE
Support different domains config at runtime

### ISSUE THREAD

**Issue by existe-deja** [nuxt-modules/i18n#2443]
### Describe the feature

One build to rule them all!
A good practice is to be able to deliver a project on a staging or prod environment just but changing some environment variables. It would be nice to have the ability to set the related domain for a locale at runtime level.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution) (The contribution guideline of nuxt-modules/i18n is compliant with Nuxt too).
- [X] Check existing [discussions](https://github.com/nuxt-modules/i18n/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by cjpearson** [comment]
I also need this behavior and have a WIP patch. It allows overriding a locale's domain at runtime by setting the `NUXT_PUBLIC_I18N_LOCALES_{locale}_DOMAIN` environment variable.

**Comment by BobbieGoede** [comment]
Resolved by #2446!

**Comment by existe-deja** [comment]
I think I missed something in the setup or maybe it's not working at all.

When I build my project with an certain `.env` file, domain values are not updated when I run it with another `.env` file.

To reproduce:

**1/ edit your `/etc/hosts` with at least the following content to be able to have different local domains**
```
127.0.0.1	localhost local-dev-en local-dev-nl local-dev-ja local-prod-en local-prod-nl local-prod-ja
 ```
 
**2/ clone the project https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-jvph93?file=.template.env and `yarn dev` with the following `.env`**
```
NUXT_PUBLIC_I18N_LOCALES_EN_DOMAIN=local-dev-en:3000
NUXT_PUBLIC_I18N_LOCALES_NL_DOMAIN=local-dev-nl:3000
NUXT_PUBLIC_I18N_LOCALES_JA_DOMAIN=local-dev-ja:3000
```
Everything works fine, the domain is correctly mapped to the locale

**3/ with the same .env file, `yarn build` and then run it with the `.env`**
In Ubuntu I use this command `set -a && source .env && set +a && node .output/server/index.mjs`

Everything works fine as in dev mode.

**4/ update the `.env` file with the following values** 
```
NUXT_PUBLIC_I18N_LOCALES_EN_DOMAIN=local-prod-en:3000
NUXT_PUBLIC_I18N_LOCALES_NL_DOMAIN=local-prod-nl:3000
NUXT_PUBLIC_I18N_LOCALES_JA_DOMAIN=local-prod-ja:3000
```

**5/ run the previous build with the new values without rebuilding it** 
run `set -a && source .env && set +a && node .output/server/index.mjs` again.
The new domains are injected into the runtime config but not into the i18n module domain detection, it keeps the the env from the build time.

What am I missing? :thinking:

**Comment by existe-deja** [comment]
I think it needs to be reopened or to provide a fully working project

**Comment by bcadu** [comment]
I suspect this issue is not fixed.
I've opened a new ticket https://github.com/nuxt-modules/i18n/issues/2602
