### ISSUE TITLE
Locale ISO code is required to generate alternate link when using `installModule`

### ISSUE THREAD

**Issue by atonemi** [nuxt-modules/i18n#2590]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.17.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.11.0
- Builder:          -
- User Config:      devtools, app, modules, components, postcss
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.6, @vueuse/nuxt@10.6.1, @vant/nuxt@1.0.4, @bg-dev/nuxt-naiveui@1.6.1, @nuxt/image@1.1.0, @nuxtjs/device@3.1.1, @nuxtjs/tailwindcss@6.10.1
- Build Modules:    -- Operating System: Windows_NT
- Node Version:     v18.17.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.11.0
- Builder:          -
- User Config:      devtools, app, modules, components, postcss
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.6, @vueuse/nuxt@10.6.1, @vant/nuxt@1.0.4, @bg-dev/nuxt-naiveui@1.6.1, @nuxt/image@1.1.0, @nuxtjs/device@3.1.1, @nuxtjs/tailwindcss@6.10.1
- Build Modules:    -

### Reproduction

![image](https://github.com/nuxt-modules/i18n/assets/75244754/c8ac25fc-5d28-4523-be6c-dc32d7842d11)
![image](https://github.com/nuxt-modules/i18n/assets/75244754/4816e049-cd14-475f-94a7-7a57a8a87183)

### Describe the bug

I‘m sorry, I can only use pictures 
I am facing this problem in "rc-6" but it is normal in "rc-5" I want to know what is the reason can you tell me?

**Comment by atonemi** [comment]
I apologize. I figured out the issue myself. I made a mistake in my previous message
But,  I've encountered another issue. I'm not sure how to specify the 'langDir' options when using 'installModule' to install this module. Can you provide guidance on that?
![image](https://github.com/nuxt-modules/i18n/assets/75244754/dde52e4c-9c10-490f-b086-b2ecd0b5fe55)

https://stackblitz.com/edit/nuxt-i18n-queistion

**Comment by BobbieGoede** [comment]
I wasn't aware of `installModule`, I will have to look into that sometime. 

The reason why it isn't working is because in our logic for layer support we go through all layer configs and resolve the locales relative to each `langDir`, I'm not sure exactly where the options provided by `installModule` end up.

Specifically for `locales` and `langdir` I recommend using the [`i18n:registerModule` hook](https://i18n.nuxtjs.org/guide/extend-messages#extending-messages-hook), that is made specifically for modules providing translations and/or locales, [here is your reproduction but modified to use this hook](https://stackblitz.com/edit/nuxt-i18n-queistion-wxk8xv?file=modules%2Fi18n-resource%2Findex.ts).

Closing this issue as it has been resolved, if you have any more questions feel free to open a discussion here https://github.com/nuxt-modules/i18n/discussions!

**Comment by atonemi** [comment]
Thank you, it worked
But I'm still encountering the error: 'Locale ISO code is required to generate alternate link. because I used 'useLocaleHead'.
![image](https://github.com/nuxt-modules/i18n/assets/75244754/224882e5-886b-4233-ab5b-4834fcba1b63)
https://stackblitz.com/edit/nuxt-i18n-queistion

**Comment by atonemi** [comment]
Why did this issue arise in 'rc-6' when it wasn't a problem in 'rc-5'?

**Comment by BobbieGoede** [comment]
>Why did this issue arise in 'rc-6' when it wasn't a problem in 'rc-5'?

Hmm, did this work without issues in `rc.5` specifically using `installModule`? When installing the module inside Nuxt configuration it works as expected, I changed [the reproduction again to demonstrate](https://stackblitz.com/edit/nuxt-i18n-queistion-wxk8xv?file=nuxt.config.ts).

**Comment by atonemi** [comment]
I'm trying to manage the language options through the admin panel as it aligns with my business requirements. So, I attempted to use it within the modules

**Comment by atonemi** [comment]
I confirmed it is working in rc-5

**Comment by BobbieGoede** [comment]
Could you provide a reproduction of it working using `rc.5`? I think I may be misunderstanding your issue.

**Comment by atonemi** [comment]
https://stackblitz.com/edit/nuxt-i18n-queistion-ckrqt7?file=nuxt.config.ts,package.json,modules%2Fi18n-resource%2Findex.ts
The current usage of 'registerModule' and 'installModule' only works in rc-5; it doesn't work in rc-6 and rc-7
You can try updating '@nuxtjs/i18n' to either rc-6 or rc-7 versions (without modifying any code)

**Comment by atonemi** [comment]
I need this usage because it's crucial for my business. I hope the issue can be resolved in the official v8 release. I would greatly appreciate it. Thank you so much!

**Comment by BobbieGoede** [comment]
Thank you for providing the reproduction! I think I know what might be the cause of this regression, hopefully I can fix it later today.

**Comment by atonemi** [comment]
Thank you for your hard work

**Comment by BobbieGoede** [comment]
@yapengsoft 
The fix has been merged and is now included in the edge channel, I have changed the reproduction to demonstrate [here](https://stackblitz.com/edit/nuxt-i18n-queistion-lwh4fd?file=package.json). You may need to remove `node_modules` and lockfiles before installing!
