### ISSUE TITLE
Error with Nuxt 3.16: Vue I18n configuration file does not exist at ./i18n/i18n.config.ts

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/i18n#3394]
### Environment

Just upgraded to Nuxt 3.16 and got this warning:

```
[@nuxtjs/i18n 2:05:46 PM]  WARN  Ignore Vue I18n configuration file does not exist at ./i18n/i18n.config.ts in /Users/mick/git/my-project. Skipping...
```

But more important: i18n.config is actually NOT loaded anymore.

Config:

```ts
export default defineNuxtConfig({
  ..
  future: {
    compatibilityVersion: 4,
  },
  i18n: {
    vueI18n: './i18n/i18n.config.ts',
  }
});
```

Location of i18n folder: `./i18n/i18n.config.ts`

<img width="215" alt="Image" src="https://github.com/user-attachments/assets/73148a1d-a921-4b14-92f8-bd8f41b1b6e9" />

**Comment by rigtigeEmil** [comment]
I'm experiencing the same issue, although I don't have my config file in the `i18n` directory, but in the root of the app. Moving it to the `i18n` directory doesn't work either

**Comment by layerzzzio** [comment]
Same problem here

**Comment by basilky** [comment]
I was on nuxt-i18n version 9.2.1, and i18n was working. I'm still on the same version but suddenly this error is coming

**Comment by BobbieGoede** [comment]
@basilky 
Could you provde a reproduction of a project setup that works in 9.2.1 but does not work in 9.3? The change in vue-i18n config resolution should be the same since v9 (resolved from `<rootDir>/i18n` unless `restructureDir` has been configured) .

**Comment by layerzzzio** [comment]
FYI the way I solved it (after migrating to Nuxt 3.16 and the i18n module v9.3.0)

<img width="225" alt="Image" src="https://github.com/user-attachments/assets/db36dae4-8f8b-419e-abb9-b63cc13a2ed6" />

And then this parameter in the nuxt config `vueI18n: "./i18n.config.ts"`

**Comment by juni0r** [comment]
Can confidently confirm this was introduced by 9.3.0. I did nothing but upgrade from 9.2.1 and 💥**BOOM**💥 suddenly it doesn't find `i18n.config.ts` where it's been residing since the dawn of time without any issues.

Config: 

```js
  i18n: {
    vueI18n: './i18n.config.ts',
    locales: ['en', 'es', 'fr', 'de', 'it'],
    defaultLocale: 'en',
    strategy: 'no_prefix',
  },
```

Changing `vue18n` to `../i18n.config.ts` (note the double dots) will fix it, so it's apparently expected to live in `i18n` which isn't even a standard folder name. This is breaking behavior right there, so you might want to address this.

**EDIT:** It's behaving just as advertised, see below.

**Comment by MickL** [comment]
So possibly this is not because of Nuxt 3.16 but because of nuxt i18n 9.3.0?

**Comment by BobbieGoede** [comment]
>Changing vue18n to ../i18n.config.ts (note the double dots) will fix it, so it's apparently expected to live in i18n which isn't even a standard folder name. This is breaking behavior right there, so you might want to address this.
@juni0r 

This is documented in the [migration guide for v9](https://i18n.nuxtjs.org/docs/guide/migrating#directory-restructure-and-langdir-default-value), i18n files are resolved from the `i18n` directory unless configured via `restructureDir`. 

I'm surprised the configurations shared here worked with 9.2.1, this is unexpected behavior 🤔 I have made various changes to the file resolution to add HMR support, this likely corrected this resolution.

**Comment by BobbieGoede** [comment]
The warning message does point to the wrong directory, I have just released [`v9.3.1`](https://github.com/nuxt-modules/i18n/releases/tag/v9.3.1) which improves the message to print the actual directory in which we are trying to find the vue-i18n config file to avoid further confusion.

**Comment by juni0r** [comment]
@BobbieGoede Thanks for pointing this out. When I upgraded to v9 I didn't change the config from v8, I remember being surprised it worked but didn't give it much thought.

My bad, it's documented behavior and I just didn't get the memo. Thank you for your time and support and also for making the error message more helpful.

**Comment by mcfarljw** [comment]
I can confirm that `v9.3.1` provides a better message to which directory it's looking for the `i18n.config.ts` file so for me I have to do this:

```ts
future: {
  compatibilityVersion: 4,
},
i18n: {
  ...
  vueI18n: '../app/i18n.config.ts',
},
```

https://i18n.nuxtjs.org/docs/guide/migrating#directory-restructure-and-langdir-default-value didn't catch this change and had my config in the app directory because I always considered them client related but after thinking about it root directory probably makes more sense because of server-side translations.

*I'll probably open a bug or feature request for it but I think it'd be more intuitive if when setting `vueI18n` it's from the project root rather than the `i18n` directory.* I opened it https://github.com/nuxt-modules/i18n/issues/3399 as a bug report here.

**Comment by MickL** [comment]
I didnt see that too: 

> All i18n files are resolved relative to <rootDir>/i18n, this can be configured with the restructureDir option.

Weird tho that it was working before and suddenly doesnt anymore. So I ended up removing `vueI18n` from `i18n` config so it gets the default option, and the file stayed at `<rootDir>/i18n/i18n.config.ts`.

**Comment by TheDutchCoder** [comment]
I know this is technically closed, but just want to say that this is still broken if you use a `srcDir` in the Nuxt config.
We get the warning `Vue I18n configuration file ./i18n.config.ts not found in [redacted]/web-client/src. Skipping...`, which makes no sense, because the config lives in the root, not in `./src`.

Moving the config file to the `src` dir breaks the entire app (`[nuxt] [request error] [unhandled] [500] $setup.t is not a function`), also configuring it as `../i18n.config.ts` breaks it.

We can't seem to get this to work anymore, regardless of moving the config file or changing config settings.

Just to clarify: I think it actually works (the config file), but the warning is incorrect.

**Comment by BobbieGoede** [comment]
@TheDutchCoder 
Could you open a new issue with a minimal reproduction? 🙏
